name: Build driver
on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: raspi_dev
            script: ./install_dev_pi.sh
            base_image: https://downloads.raspberrypi.com/raspios_lite_arm64/images/raspios_lite_arm64-2024-07-04/2024-07-04-raspios-bookworm-arm64-lite.img.xz
          - name: snakeyes
            script: ./install_snakeyes.sh
            base_image: https://downloads.raspberrypi.com/raspios_lite_arm64/images/raspios_lite_arm64-2024-07-04/2024-07-04-raspios-bookworm-arm64-lite.img.xz
          - name: opi5
            script: ./install_opi5.sh
            base_image: https://github.com/Joshua-Riek/ubuntu-rockchip/releases/download/v2.4.0/ubuntu-24.04-preinstalled-server-arm64-orangepi-5.img.xz
          - name: rubikpi3
            script: ./install_opi5.sh
            base_image: https://testisdfasdfasdf.s3.us-east-2.amazonaws.com/ubuntu-24.04-preinstalled-desktop-arm64-rubikpi3.img.xz?response-content-disposition=inline&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Security-Token=IQoJb3JpZ2luX2VjEJ7%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaCXVzLWVhc3QtMiJGMEQCIBhyPZGFCmyv5rUv%2BgO2FAUUjf5eoHEk4MTqWbCi3nETAiBNbT0e%2BEmqXhRdZM6RwbDlmGIBjC9QQiJ6QXXbb7KbhSrCAwjH%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F8BEAAaDDA5MzExMzI5MDQ5NyIM5PguvDZkrIkbKi5yKpYDPMchIDmAthtknZlOGTmsrEQnNHBSzqBGsfrm%2BYwNReTbCoyw8o%2FZTn%2F1urQO7ixsdPNxonAyanZvOEgjKQCDTayAmLGBKx6t3w6uXSszW4zQ9KXJFO%2F4yoAvf8enIRqmeqZAzOnrn%2FsYtqItpPWfDnLHbcLw5alyURayOPPmviKMp3uvQTYZzOnLZw2SXyueIyjM9n3fncT2TafPGuwdCjPqzAwPEdrYjWm0DX3xH2mchqlvfjpCCJsYY0KivxDw4pCxwJdDcsw5mPd7dBDegfgBgWLsjdZrbxc%2FHhTZpQYCWITr2EP3dm2jBkB%2FGL9zohOLxxWLMdMgD7VIVjxu%2B4pFjkEJKSgtc37NGZbg2qMdV7ANBKyVtTyteu64Sm%2BfgqDGVFEGzi8pMbZLvR3PeKfQtks3vPjbXuaLXLy6GoLzuX%2FxVyNy1trAj52M7%2FGXzHu%2FZ7J0xAUrYoWkJERD1vyzIG1JS7mEbTtbo7lNs5qJCVmbgydI1nh67CvkZUlEGPyQQSn1oYKaZ2IJX%2F83HEYlSK3byjCUiqnEBjrfAqPvVtEUxn2MHLhoCSpdk7QXgfK5IMlRDZ2P4q%2FZqML1fd7UPU9QnhzdrCx3Jvte9pQt1TPoQ4SLJ%2BkBSykum02NhoyPdMsVMpry0hBfSsM8DuQ%2FIDNyU5Gt0QqQ4sKXL%2B1gi%2BR4KK4JB1YO8BjbrlfYjV6d58hGbQfY%2BTKP7qO7iLTxnm7MYoV4cor1PJz74pbZugQ%2Fzz4o06OxndVFYOcAjk0xqThcSXQ%2BuGcybDcTfGc01quCTmXZmXJCnEIbO2xi%2Boi%2FpDKECNqsCBZy%2F1Fe8k56QGIy26XuTYjNvQE3JQgvos%2FAibxvvTezaQmBNTSmpjxn74DNeSDpXd3se4k1Sf1x2%2FOTnQuEMZNeYiDMplhT5U0xI980CvNLUmLp13S3ymzQ2qt0dkOo1oFYswSYNLrF672%2Fp%2B5k4lN79Gx3%2B10Ze81EVF4PkL08qw1%2BMpYsr4k7Akm%2Bq9DzKbblKw%3D%3D&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=ASIARLLP4B4A362GXYP2%2F20250730%2Fus-east-2%2Fs3%2Faws4_request&X-Amz-Date=20250730T214946Z&X-Amz-Expires=1200&X-Amz-SignedHeaders=host&X-Amz-Signature=b2d6c75c5bbbcf2b5ce31ead47a5e8ed1f6c50e1cd7b82f20f2aa169e9c669aa
            
    name: "Build for ${{ matrix.name }}"

    steps:
    - uses: actions/checkout@v4.1.7
      with:
        fetch-depth: 0
    - name: Fetch tags
      run: git fetch --tags --force

    - uses: pguyot/arm-runner-action@HEAD
      id: install_deps
      with:
        image_additional_mb: 1500
        bind_mount_repository: true
        base_image: ${{ matrix.base_image }}
        commands: |
          chmod +x ${{matrix.script}}
          ${{ matrix.script }}
          chmod +x ./install_common.sh
          ./install_common.sh
          mkdir -p /opt/photonvision/
          echo "${{ github.ref_name }};${{ matrix.name }}" > /opt/photonvision/image-version

    - name: Compress built image
      run: |
        mv ${{ steps.install_deps.outputs.image }} photonvision_${{ matrix.name }}.img
        sudo xz -T 0 -v photonvision_${{ matrix.name }}.img

    - uses: actions/upload-artifact@v4.3.4
      with:
        name: photonvision_${{ matrix.name }}.img.xz
        path: photonvision_${{ matrix.name }}.img.xz
        if-no-files-found: error
        retention-days: 1

  release:
    needs: [build]
    runs-on: ubuntu-22.04
    steps:
      # Download literally every single artifact
      - uses: actions/download-artifact@v4.1.8
      - run: find
      # Push to dev release
      - uses: pyTooling/Actions/releaser@v1.0.5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: 'Dev'
          rm: true
          files: |
            **/*.xz
        if: github.event_name == 'push'
      # Upload all xz archives to GH tag if tagged
      - uses: softprops/action-gh-release@v2.0.8
        with:
          files: |
            **/*opi5*.xz
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: softprops/action-gh-release@v2.0.8
        with:
          files: |
            **/!(*opi5*).xz
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}