name: Build driver
on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: raspi_dev
            script: ./install_dev_pi.sh
            base_image: https://downloads.raspberrypi.com/raspios_lite_arm64/images/raspios_lite_arm64-2024-07-04/2024-07-04-raspios-bookworm-arm64-lite.img.xz
          - name: snakeyes
            script: ./install_snakeyes.sh
            base_image: https://downloads.raspberrypi.com/raspios_lite_arm64/images/raspios_lite_arm64-2024-07-04/2024-07-04-raspios-bookworm-arm64-lite.img.xz
          - name: opi5
            script: ./install_opi5.sh
            base_image: https://github.com/Joshua-Riek/ubuntu-rockchip/releases/download/v2.4.0/ubuntu-24.04-preinstalled-server-arm64-orangepi-5.img.xz
          - name: rubikpi3
            script: ./install_opi5.sh
            base_image: https://testisdfasdfasdf.s3.us-east-2.amazonaws.com/ubuntu-24.04-preinstalled-desktop-arm64-rubikpi3.img.xz?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=ASIARLLP4B4A3PU4NM3V%2F20250730%2Fus-east-2%2Fs3%2Faws4_request&X-Amz-Date=20250730T214520Z&X-Amz-Expires=300&X-Amz-Security-Token=IQoJb3JpZ2luX2VjEJ7%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaCXVzLWVhc3QtMiJIMEYCIQDJ%2B2F%2FaPFRwyvMEmh%2B7l%2B6C12xOGUreWwxRhh5%2BMZMxwIhAO6Pvfne5dmy2R%2F2DJ5jjvHVDn581DovEPCDzC9PjCCHKuQCCMf%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEQABoMMDkzMTEzMjkwNDk3IgylpKWPeT55TTaEUwUquAIcxtaZc6pK6S2plh%2BJyyQ%2BX4klnVMdd5G9f7jVk%2BMJ9nCTtdkCnMMmGfI8S2sGlLDweki3Z9K6KVOYpMf6TKNNfGrTch8DNRdiRTZ0z6EqGvoMiLNomd9nJCozB%2FEu2kVgKOq6VF%2B1lTBifVXiJ69%2Fc6P6GSHcaLpEW%2F4sCPX1dTyBGCrBOueA233ScH7jt6iPyHn461qJ1dQPTTG%2BwBjP2EJhgIX5Up7z2fhmDUq2ZFrWLmXeFmSqn5aU9Pvp9EGMWcxLPlENDgvh405Rcmnu4%2BcvslGDI95kq%2BSmhAajemCc%2FJvCH6n7DgVLjgUfu%2BN%2FVP%2BxtDoWm10TuxIWT%2F%2B5MUkKEy8qnyyEdrfS2KwxZDz3G9BcXuF2DvSOGySRf2nGV8VvIMDvVg1jZ9l25WkI%2FHDXyhsQbtwwlIqpxAY6rALMijg%2BOOPWRqCteS9honlOXs0jplT3Iu1EJl4emwaKglU4YxefIHTGrYQzsWOBElKpEa%2FTHOpQhlWcClXIEBujkizWoooEX8HwXDigYt5sztlLsGNdyIbQfqLC4VLTRGhdPZf%2BOdSE46%2F%2B%2BSC44xg4nNEwkgPXKwC8ETkBGVDtblmtB7SpG9aP5cUqeecfdAElZacHfpD62o6%2BRyYbJ5C45bupaIL2RXzj9fkj9AkmhNqWbflFOCwmHyltFSGGA5HKwfFFRxwOxPIMOOryxciQq5QMrdCrtI0FtxmMoPJ7WB8Zjn2PlKVK%2BRbC1Mn1aWgW%2F%2Bmjntkdz%2BtPCON5uI4ZWqkmmGKw1utztxMZRUKfjvRkm7gDsv8BC4y33g7aqEL%2BCALeZBnwdrcaZLc%3D&X-Amz-Signature=2a72e63ebd522624ead0fb070215d2e57fdc6d7b9fbc4677d3d83db53ee94987&X-Amz-SignedHeaders=host&response-content-disposition=attachment
            
    name: "Build for ${{ matrix.name }}"

    steps:
    - uses: actions/checkout@v4.1.7
      with:
        fetch-depth: 0
    - name: Fetch tags
      run: git fetch --tags --force

    - uses: pguyot/arm-runner-action@HEAD
      id: install_deps
      with:
        image_additional_mb: 1500
        bind_mount_repository: true
        base_image: ${{ matrix.base_image }}
        commands: |
          chmod +x ${{matrix.script}}
          ${{ matrix.script }}
          chmod +x ./install_common.sh
          ./install_common.sh
          mkdir -p /opt/photonvision/
          echo "${{ github.ref_name }};${{ matrix.name }}" > /opt/photonvision/image-version

    - name: Compress built image
      run: |
        mv ${{ steps.install_deps.outputs.image }} photonvision_${{ matrix.name }}.img
        sudo xz -T 0 -v photonvision_${{ matrix.name }}.img

    - uses: actions/upload-artifact@v4.3.4
      with:
        name: photonvision_${{ matrix.name }}.img.xz
        path: photonvision_${{ matrix.name }}.img.xz
        if-no-files-found: error
        retention-days: 1

  release:
    needs: [build]
    runs-on: ubuntu-22.04
    steps:
      # Download literally every single artifact
      - uses: actions/download-artifact@v4.1.8
      - run: find
      # Push to dev release
      - uses: pyTooling/Actions/releaser@v1.0.5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: 'Dev'
          rm: true
          files: |
            **/*.xz
        if: github.event_name == 'push'
      # Upload all xz archives to GH tag if tagged
      - uses: softprops/action-gh-release@v2.0.8
        with:
          files: |
            **/*opi5*.xz
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: softprops/action-gh-release@v2.0.8
        with:
          files: |
            **/!(*opi5*).xz
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}