name: Build driver
on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: limelight
            script: ./install_limelight.sh
            base_image: https://downloads.raspberrypi.com/raspios_lite_arm64/images/raspios_lite_arm64-2024-07-04/2024-07-04-raspios-bookworm-arm64-lite.img.xz
          - name: limelight3
            script: ./install_limelight3.sh
            base_image: https://downloads.raspberrypi.com/raspios_lite_arm64/images/raspios_lite_arm64-2024-07-04/2024-07-04-raspios-bookworm-arm64-lite.img.xz
          - name: limelight3g
            script: ./install_limelight3g.sh
            base_image: https://downloads.raspberrypi.com/raspios_lite_arm64/images/raspios_lite_arm64-2024-07-04/2024-07-04-raspios-bookworm-arm64-lite.img.xz
          - name: raspi
            script: ./install_pi.sh
            base_image: https://downloads.raspberrypi.com/raspios_lite_arm64/images/raspios_lite_arm64-2024-07-04/2024-07-04-raspios-bookworm-arm64-lite.img.xz
          - name: raspi_dev
            script: ./install_dev_pi.sh
            base_image: https://downloads.raspberrypi.com/raspios_lite_arm64/images/raspios_lite_arm64-2024-07-04/2024-07-04-raspios-bookworm-arm64-lite.img.xz
          - name: snakeyes
            script: ./install_snakeyes.sh
            base_image: https://downloads.raspberrypi.com/raspios_lite_arm64/images/raspios_lite_arm64-2024-07-04/2024-07-04-raspios-bookworm-arm64-lite.img.xz
          - name: opi5
            script: ./install_opi5.sh
            base_image: https://github.com/Joshua-Riek/ubuntu-rockchip/releases/download/v2.4.0/ubuntu-24.04-preinstalled-server-arm64-orangepi-5.img.xz
          - name: opi5b
            script: ./install_opi5.sh
            base_image: https://github.com/Joshua-Riek/ubuntu-rockchip/releases/download/v2.4.0/ubuntu-24.04-preinstalled-server-arm64-orangepi-5b.img.xz
          - name: opi5plus
            script: ./install_opi5.sh
            base_image: https://github.com/Joshua-Riek/ubuntu-rockchip/releases/download/v2.4.0/ubuntu-24.04-preinstalled-server-arm64-orangepi-5-plus.img.xz
          - name: opi5pro
            script: ./install_opi5.sh
            base_image: https://github.com/Joshua-Riek/ubuntu-rockchip/releases/download/v2.4.0/ubuntu-24.04-preinstalled-server-arm64-orangepi-5-pro.img.xz
          - name: opi5max
            script: ./install_opi5.sh
            base_image: https://github.com/Joshua-Riek/ubuntu-rockchip/releases/download/v2.4.0/ubuntu-24.04-preinstalled-server-arm64-orangepi-5-max.img.xz
          - name: rock5c
            script: ./install_opi5.sh
            base_image: https://github.com/Joshua-Riek/ubuntu-rockchip/releases/download/v2.4.0/ubuntu-24.04-preinstalled-server-arm64-rock-5c.img.xz
          - name: rubikpi3
            script: ./install_rubikpi3.sh
            base_image: https://testisdfasdfasdf.s3.us-east-2.amazonaws.com/ubuntu-24.04-preinstalled-desktop-arm64-rubikpi3.img.xz?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=ASIARLLP4B4AXA3LBM5R%2F20250730%2Fus-east-2%2Fs3%2Faws4_request&X-Amz-Date=20250730T205449Z&X-Amz-Expires=300&X-Amz-Security-Token=IQoJb3JpZ2luX2VjEJ3%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaCXVzLWVhc3QtMiJGMEQCIENKgJe0n8Wymt8AhAc0TdV6dJ2U32rQVKqNq66M%2B%2FCjAiBqMhP5G5lAeK586amR5es44uDKK%2FI4bS3THOhdugowECrkAgjG%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F8BEAAaDDA5MzExMzI5MDQ5NyIM9Js6K%2BtvojDMQ2U0KrgCRIELY91h%2F7WvvItvgu%2FyzdRLfAMiJdG7p80HoG5N0rYHKn%2FychmMqnRJjz5Zk4tYLdfDeBxUcFpXHbur050xHJ5h4Tvgs5TbumzpbcEwmAj0J7a%2FWOlnCUuDciPxISSHCv1UKdOrlt57nDK%2BFBlw2VH7kMzGkdXXaIklPUBVwVT0wjBezucOvxWcuA5FLCq%2BrSAXkLMNJhnkXUSsvQ4zTAADa3ieFsilHK1jrZTzQRNPtv0p0210zwZz6CzvoADkhAtV937nuHSzBPJ3d5ydLerw4yYyb1DMyXY%2BXt3lld9XiAeVxN%2B1p270D9G3jBKYME99kyKYkx2ZjtB1RKArFb2frm98VoBdB7enYymKGRRSu3o14HgghHe%2BfjL2g%2BVTc2BW4aLbT4K904BIgg2vumCs9BgFSa95MJSKqcQGOq4COtoUXBSS125s2W1ny5gkEuRI3%2Fn9Uq9hi7i4aqImeDXIU8EPKrEOtEG168eu%2FTbksLqOjUkjM%2FNopn78EB2u8fq3Iw2WZ55%2FcnzsfPmjgbrHhU405e88KllBz%2FF6VR32Fda0%2BuTV6ifVvLxL%2FyWhNcL%2Fe8lhS7%2B%2BK9IQBXXrSjF3ZA1GpWn55kWUIFu1guDXYf%2BlNQfS94QnGRKSlrWlpf6XH8uELooxNS%2BXGZRoZ1lllh8w3ULc22Ijk%2F6wUZ8TMalNrdFn1NkcVlhilCh73HzbJQAEIl1LNf3womQC9F%2FwLrBApM%2BR7IYhNQHU8BY5rsGVVvzB6B74aM3GfA7RUWZIf17MtQsGNJ0zNUsPF3iEDmL%2Bggizb4JqMxaHTJRJcvyrqneS2VcOldiD%2BU0%3D&X-Amz-Signature=e9c983963dfd3339e330a188be66a48be354fc706526a090c433b200bce53994&X-Amz-SignedHeaders=host&response-content-disposition=attachment
            
    name: "Build for ${{ matrix.name }}"

    steps:
    - uses: actions/checkout@v4.1.7
      with:
        fetch-depth: 0
    - name: Fetch tags
      run: git fetch --tags --force

    - name: Pre-process rubikpi3 image if needed
      if: matrix.name == 'rubikpi3'
      run: |
        echo "Downloading and extracting rubikpi3 .tgz file..."
        wget -O rubikpi3.tgz "${{ matrix.base_image }}"
        tar -xzf rubikpi3.tgz
        # Find the .img.xz file in the extracted contents
        IMG_FILE=$(find . -name "*.img.xz" | head -1)
        if [ -n "$IMG_FILE" ]; then
          mv "$IMG_FILE" rubikpi3.img.xz
          echo "Extracted image: rubikpi3.img.xz"
        else
          echo "Error: No .img.xz file found in the archive"
          exit 1
        fi

    - uses: pguyot/arm-runner-action@v2.6.5
      id: install_deps
      with:
        image_additional_mb: 1500
        bind_mount_repository: true
        base_image: ${{ matrix.name == 'rubikpi3' && format('file://{0}/rubikpi3.img.xz', github.workspace) || matrix.base_image }}
        commands: |
          chmod +x ${{matrix.script}}
          ${{ matrix.script }}
          chmod +x ./install_common.sh
          ./install_common.sh
          mkdir -p /opt/photonvision/
          echo "${{ github.ref_name }};${{ matrix.name }}" > /opt/photonvision/image-version

    - name: Compress built image
      run: |
        mv ${{ steps.install_deps.outputs.image }} photonvision_${{ matrix.name }}.img
        sudo xz -T 0 -v photonvision_${{ matrix.name }}.img

    - uses: actions/upload-artifact@v4.3.4
      with:
        name: photonvision_${{ matrix.name }}.img.xz
        path: photonvision_${{ matrix.name }}.img.xz
        if-no-files-found: error
        retention-days: 1

  release:
    needs: [build]
    runs-on: ubuntu-22.04
    steps:
      # Download literally every single artifact
      - uses: actions/download-artifact@v4.1.8
      - run: find
      # Push to dev release
      - uses: pyTooling/Actions/releaser@v1.0.5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: 'Dev'
          rm: true
          files: |
            **/*.xz
        if: github.event_name == 'push'
      # Upload all xz archives to GH tag if tagged
      - uses: softprops/action-gh-release@v2.0.8
        with:
          files: |
            **/*opi5*.xz
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: softprops/action-gh-release@v2.0.8
        with:
          files: |
            **/!(*opi5*).xz
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
